force-app/main/default/objects/External_Trainer__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Location__c</fullName>
        <label>Assigned Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fairfax</fullName>
                </value>
                <value>
                    <fullName>SPS</fullName>
                </value>
                <value>
                    <fullName>Reston</fullName>
                </value>
                <value>
                    <fullName>UTA-ERB</fullName>
                </value>
                <value>
                    <fullName>USF-NEC</fullName>
                </value>
                <value>
                    <fullName>ASU</fullName>
                </value>
                <value>
                    <fullName>WVU-CBE</fullName>
                </value>
                <value>
                    <fullName>Queens</fullName>
                </value>
                <value>
                    <fullName>USF-SOC</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>USF-BSN</fullName>
                </value>
                <value>
                    <fullName>UTA-PRS</fullName>
                </value>
                <value>
                    <fullName>UTA-K</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Skills__c</fullName>
        <label>Training Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appian BPM</fullName>
                </value>
                <value>
                    <fullName>Big Data/Hadoop</fullName>
                </value>
                <value>
                    <fullName>Business Analyst</fullName>
                </value>
                <value>
                    <fullName>Dynamics CRM</fullName>
                </value>
                <value>
                    <fullName>ETL/Informatics</fullName>
                </value>
                <value>
                    <fullName>Full Stack .NET</fullName>
                </value>
                <value>
                    <fullName>Full Stack Java/JEE</fullName>
                </value>
                <value>
                    <fullName>Full Stack JTA</fullName>
                </value>
                <value>
                    <fullName>Microservices</fullName>
                </value>
                <value>
                    <fullName>Oracle Fusion Middleware</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pega</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>System Admin</fullName>
                </value>
                <value>
                    <fullName>Web Tools</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Trainer</label>
    <nameField>
        <label>External Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Trainers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/afExtTabListViewApexControllerTest.cls
@isTest
public class afExtTabListViewApexControllerTest {

    private static List<External_Trainer__c> xtrainers;

    @TestSetup
    public static void doSetup(){

        xtrainers = UtilityMethods.createExternalTrainerData(50);
        insert xtrainers;
        
    }
    
    @isTest
    public static void allTrainersTest(){

        xtrainers = [SELECT Id, First_Name__c, Last_Name__c, Available__c, Training_Skills__c, Current_Location__c
                     FROM External_Trainer__c];

        Test.startTest();

        List<External_Trainer__c> results = afExtTrainersTabListViewApexController.allTrainers();

        Test.stopTest();

        System.assertNotEquals(results,null);
        System.assertEquals(results.size(),xtrainers.size());
        for (External_Trainer__c x : results){
            System.assert(xtrainers.contains(x));
        }
    }

    @isTest
    public static void getTrainerSkillsTest(){

        xtrainers = [SELECT id FROM External_Trainer__c];

        Test.startTest();

        for (External_Trainer__c x : xtrainers) {
            String result = afExtTrainersTabListViewApexController.getTrainerSkills(x.id);
            System.assertEquals(result, 'Other, Pega, Salesforce');
        }

        Test.stopTest();
    }
}