force-app/main/default/objects/External_Trainer__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Location__c</fullName>
        <label>Assigned Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fairfax</fullName>
                </value>
                <value>
                    <fullName>SPS</fullName>
                </value>
                <value>
                    <fullName>Reston</fullName>
                </value>
                <value>
                    <fullName>UTA-ERB</fullName>
                </value>
                <value>
                    <fullName>USF-NEC</fullName>
                </value>
                <value>
                    <fullName>ASU</fullName>
                </value>
                <value>
                    <fullName>WVU-CBE</fullName>
                </value>
                <value>
                    <fullName>Queens</fullName>
                </value>
                <value>
                    <fullName>USF-SOC</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>USF-BSN</fullName>
                </value>
                <value>
                    <fullName>UTA-PRS</fullName>
                </value>
                <value>
                    <fullName>UTA-K</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Skills__c</fullName>
        <label>Training Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appian BPM</fullName>
                </value>
                <value>
                    <fullName>Big Data/Hadoop</fullName>
                </value>
                <value>
                    <fullName>Business Analyst</fullName>
                </value>
                <value>
                    <fullName>Dynamics CRM</fullName>
                </value>
                <value>
                    <fullName>ETL/Informatics</fullName>
                </value>
                <value>
                    <fullName>Full Stack .NET</fullName>
                </value>
                <value>
                    <fullName>Full Stack Java/JEE</fullName>
                </value>
                <value>
                    <fullName>Full Stack JTA</fullName>
                </value>
                <value>
                    <fullName>Microservices</fullName>
                </value>
                <value>
                    <fullName>Oracle Fusion Middleware</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pega</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>System Admin</fullName>
                </value>
                <value>
                    <fullName>Web Tools</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Trainer</label>
    <nameField>
        <label>External Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Trainers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PTO__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Needs to be Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PTO Request</label>
    <nameField>
        <displayFormat>PTO-{0000}</displayFormat>
        <label>PTO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Track__c</fullName>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Trainer</label>
        <referenceTo>External_Trainer__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>Access__c</fullName>
        <label>Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open Access</fullName>
                </value>
                <value>
                    <fullName>Fob Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OfficeName__c</fullName>
        <label>Office Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Training Location</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Training Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Room__c.object
<CustomObject>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <label>Training Location ID</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Training Rooms</relationshipLabel>
        <relationshipName>Training_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Room</label>
    <nameField>
        <label>Training Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>&quot;Available&quot;</defaultValue>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Skills__c</fullName>
        <description>Contains Training Tracks that the trainer has experience training. When a trainer completes a batch that has a Training Track they had previously not trained, their Training Skills list should be updated to include the new Training Track value.</description>
        <label>Training Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Tracks</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Training_Tracks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Appian BPM</fullName>
    </customValue>
    <customValue>
        <fullName>Big Data/Hadoop</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamics CRM</fullName>
    </customValue>
    <customValue>
        <fullName>ETL/Informatics</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack .NET</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack Java/JEE</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack JTA</fullName>
    </customValue>
    <customValue>
        <fullName>Microservices</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Fusion Middleware</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pega</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>System Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Web Tools</fullName>
    </customValue>
    <description>Batch types available, can be used to keep track of the types of batches that trainers have performed.</description>
    <masterLabel>Training Tracks</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UtilityMethods.cls
@isTest
public class UtilityMethods {
    
    // Create dummy Users and return them in a List.
    public static List<User> createUserData(Integer amount) {
    
        List<User> result = new List<User>();
        ID profID = [SELECT Id FROM Profile WHERE Name = 'Trainer' LIMIT 1].id;
        ID roleID = [SELECT id,name FROM UserRole WHERE name = 'Trainer' LIMIT 1].id;

        for(Integer i = 0; i < amount; i++){
            User uData = new User(
                ProfileId = profID,
                LastName = 'last ' + String.valueOf(i),
                Email = 'puser' + String.valueOf(i) + '@amamama.com',
                Username = 'puser' + String.valueOf(i) + System.currentTimeMillis() + '@amamama.com',
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                Available__c = 'Available',
                UserRoleId = roleID); 
            
            result.add(uData);
        }
        
    
        return result;
    }

    public static List<External_Trainer__c> createExternalTrainerData(Integer amount){
        
        List<External_Trainer__c> result = new List<External_Trainer__c>();

        for (Integer i = 0; i < amount; i++){
            External_Trainer__c x = new External_Trainer__c(First_Name__c = 'first',
                                                            Last_Name__c = 'last ' + i,
                                                            Available__c = 'Available',
                                                            Training_Skills__c = 'Other;Pega;Salesforce',
                                                            Current_Location__c = 'Fairfax');
            result.add(x);
        }

        return result;
    }
    
    // Create dummy Training_Location__c's and return them in a List.
    public static List<Training_Location__c> createLocationData(Integer amount){
    
        List<Training_Location__c> result = new List<Training_Location__c>();

        result.add(new Training_Location__c(OfficeName__c = 'Fairfax', Access__c = 'Open Access'));
    
        for(Integer i = 1; i < amount; i++) {
            Training_Location__c tLoc = new Training_Location__c(OfficeName__c = 'Fairfax' + i,
                                                                 Access__c = 'Open Access');
            result.add(tLoc);
        }
        
        return result;
    }
    
    // @TODO populate dates with something
    // Create dummy Date objects and return them in a List.
    public static List<Date> createStartDateData(Integer amount){
    
        Date today = Date.today();
        List<Date> result = new List<Date>();

        for(Integer i = 0; i < amount; i++) {
            Date sDate = (Date.today().addMonths(2*i).toStartofWeek().addDays(2));
            result.add(sDate);
        }
      
        return result;
    }
    
    // Create dummy Training_Track__c's and return them in a List.
    public static List<Training_Track__c> createTrainingTrackData(Integer amount){
        
        List<Training_Track__c> result = new List<Training_Track__c>();

        for(Integer i = 0 ; i < amount; i++) {
            Training_Track__c track = new Training_Track__c(ShortName__c = 'Track'+String.valueOf(i));
            result.add(track);
        }
        
        return result;
    }

    public static List<Skill__c> createSkillData(Integer amount, List<User> trainers, List<Training_Track__c> tracks) {

        List<Skill__c> result = new List<Skill__c>();

        for (integer i = 0; i < amount; i++) {
            Skill__c s = new Skill__c(Trainer__c = trainers.get(Math.mod(i,trainers.size())).id,
                                      Training_Track__c = tracks.get(Math.mod(i,tracks.size())).id);
            result.add(s);
        }

        return result;
    }
    
    // Create dummy Training__c's and return them in a List.
    public static List<Training__c> createTrainingsData( Integer amount, List<Training_Location__c> tLocList, List<User> tTrainerList,
                                                         List<Date> tsDateList, List<Training_Track__c> tTrackList) {
    
        List<Training__c> result = new List<Training__c>();

        for(integer i = 0; i < amount; i++) {
            Training__c training = new Training__c(TrainingLocation__c = tLocList[Math.mod(i,tLocList.size())].id,
                                                   Trainer__c = tTrainerList[Math.mod(i,tTrainerList.size())].id,
                                                   StartDate__c = tsDateList[Math.mod(i,tsDateList.size())],
                                                   EndDate__c = tsDateList[Math.mod(i,tsDateList.size())].toStartOfWeek().addDays(5),
                                                   TrainingTrack__c = tTrackList[Math.mod(i,tTrackList.size())].id);            
            result.add(training);
        }
        return result;
    }
    
    // Create dummy Training__c's and return them in a List.
    public static List<Training__c> createExternalTrainingsData( Integer amount, List<Training_Location__c> tLocList, List<External_Trainer__c> tTrainerList,
                                                                 List<Date> tsDateList, List<Training_Track__c> tTrackList) {
    
        List<Training__c> result = new List<Training__c>();

        for(integer i = 0; i < amount; i++) {
            Training__c training = new Training__c(TrainingLocation__c = tLocList[Math.mod(i,tLocList.size())].id,
                                                   External_Trainer__c = tTrainerList[Math.mod(i,tTrainerList.size())].id,
                                                   StartDate__c = tsDateList[Math.mod(i,tsDateList.size())],
                                                   EndDate__c = tsDateList[Math.mod(i,tsDateList.size())].toStartOfWeek().addDays(5),
                                                   TrainingTrack__c = tTrackList[Math.mod(i,tTrackList.size())].id);            
            result.add(training);
        }
        return result;
    }

    //Create dummy Training Rooms and return them in a list
    public static List<Training_Room__c> createRoomData(Integer amount, Training_Location__c location){

        List<Training_Room__c> result = new List<Training_Room__c>();

        for (integer i = 0; i < amount; i++) {
            Training_Room__c r = new Training_Room__c(TrainingLocation__c = location.id);
            result.add(r);
        }

        return result;
    }
    
    public static List<PTO__c> createPTOData(Integer amount, User trainer){

        List<PTO__c> result = new List<PTO__c>();

        for (Integer i = 0; i < amount; i++) {
            PTO__c p = new PTO__c(Trainer__c = trainer.id,
                                  StartDate__c = (Date.today().addMonths(2*i).addDays(2)),
                                  EndDate__c = (Date.today().addMonths(2*i).addDays(2)),
                                  Reason__c = 'Because',
                                  Status__c = 'Approved');
            result.add(p);
        }

        return result;
    }
}