force-app/main/default/objects/External_Trainer__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>External Trainer</label>
    <nameField>
        <label>External Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Trainers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Trainer</label>
        <referenceTo>External_Trainer__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TrainingClass__c</fullName>
        <formula>RIGHT(TEXT(MONTH(StartDate__c)), 2) + &apos;/&apos; + LPAD(TEXT(DAY(StartDate__c)), 2, &apos;0&apos;) + &apos; - &apos; + TrainingLocation__r.OfficeName__c + &apos; - &apos; + TrainingTrack__r.ShortName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/afExternalTrainerBatchesApexController.cls
public class afExternalTrainerBatchesApexController {

    @AuraEnabled
    public static List<Training__c> AllExternalTrainings {
       get{
           if(AllExternalTrainings == null)
           {
               AllExternalTrainings = [SELECT Id, Name, TrainingTrack__r.ShortName__c,
                               Status__c, TrainingClass__c, StartDate__c, EndDate__c, External_Trainer__r.First_Name__c, External_Trainer__r.Last_Name__c
                               FROM Training__c
                               ORDER BY StartDate__c];
           }
			
           return AllExternalTrainings;
       }
       set;
    }

    @AuraEnabled
    public static List<Training__c> currentExternalTrainings {
       get{
           if(currentExternalTrainings == null)
           {
               currentExternalTrainings = AllExternalTrainings;
           }
           return currentExternalTrainings;
       }
       set;
    }

    @AuraEnabled
    public static List<Training__c> getExtTrainingBatches() {
       return AllExternalTrainings;
    }
    
    //Used by afExternalTrainerTabBatches to get batches by external trainer id to populate data tables
    @AuraEnabled
    public static List<Training__c> getExtTrainingBatchesById(Id externalTrainerId) {
        List<Training__c> ExternalTrainings = 
            [SELECT Id, Name, TrainingClass__c, StartDate__c, EndDate__c, Status__c, TrainingTrack__r.ShortName__c, External_Trainer__r.Id
             FROM Training__c 
             WHERE (External_Trainer__r.Id = :externalTrainerId)
             ORDER BY StartDate__c];
            return ExternalTrainings;
    }

    @AuraEnabled
    public static void deleteExtBatchesServer(String[] batchIds) { 

        List<Training__c> batches = new List<Training__c>();
        
        for(integer s = 0; s < batchIds.size(); s++){
            batches.add(new Training__c(Id = batchIds[s]));
        }      

        for(Training__c t : batches) {
            for (Integer i = 0; i < AllExternalTrainings.size(); i++){
                if (t.id == AllExternalTrainings.get(i).id){
                    AllExternalTrainings.remove(i);
                    break;
                }
            }
        }
       
        delete batches;

    }

    @AuraEnabled
    public static void updateExtBatchesServer(List<Training__c> updatedBatches){
		System.debug('Batches to Update: ' + updatedBatches);
        
        for(integer s = 0; s < updatedBatches.size(); s++){
            if(updatedBatches[s].StartDate__c != null)
            {
                updatedBatches[s].StartDate__c = updatedBatches[s].StartDate__c.addDays(-1);
                System.debug('after subtract day: ' + updatedBatches[s]);
            }
            else if(updatedBatches[s].EndDate__c != null)
            {
                updatedBatches[s].EndDate__c = updatedBatches[s].EndDate__c.addDays(-1);
                System.debug('after subtract day: ' + updatedBatches[s]);
            }
        }
        
        update updatedBatches;
        
    }

}