force-app/main/default/objects/External_Trainer__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>External Trainer</label>
    <nameField>
        <label>External Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Trainers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Trainer</label>
        <referenceTo>External_Trainer__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingClass__c</fullName>
        <formula>RIGHT(TEXT(MONTH(StartDate__c)), 2) + &apos;/&apos; + LPAD(TEXT(DAY(StartDate__c)), 2, &apos;0&apos;) + &apos; - &apos; + TrainingLocation__r.OfficeName__c + &apos; - &apos; + TrainingTrack__r.ShortName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Location__c.object
<CustomObject>
    <label>Training Location</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Training Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/afExtBatchesApexControllerTest.cls
@isTest
public class afExtBatchesApexControllerTest {

    private static List<Training_Location__c> locations;
    private static List<External_Trainer__c> xtrainers;
    private static List<Training_Track__c> tracks;
    private static List<Training__c> trainings;


    @TestSetup
    public static void doSetup(){

        //Setup test data: Locations, Training Tracks, Trainings, User
        //UtilityMethods is last method in this class
        locations = UtilityMethods.createLocationData(6);
        xtrainers = UtilityMethods.createExternalTrainerData(3);       
        tracks = UtilityMethods.createTrainingTrackData(3);
        trainings = UtilityMethods.createExternalTrainingsData(9, locations, xtrainers, UtilityMethods.createStartDateData(9), tracks);

        insert xtrainers;
        insert locations;
        insert tracks;
        insert trainings;       

    }
    
    @isTest
    public static void doTest(){

        List <Training__c> AllTrainings = [SELECT Id, Name, TrainingTrack__r.ShortName__c, Status__c, TrainingClass__c, StartDate__c, 
                                                  EndDate__c, External_Trainer__r.First_Name__c, External_Trainer__r.Last_Name__c
                                          FROM Training__c
                                          ORDER BY StartDate__c];

        //test that the soql queries in the controller are as expected
        system.assertEquals(AllTrainings, afExternalTrainerBatchesApexController.AllExternalTrainings);
        system.assertEquals(AllTrainings, afExternalTrainerBatchesApexController.currentExternalTrainings);

        //test getter
        system.assertEquals(AllTrainings, afExternalTrainerBatchesApexController.getExtTrainingBatches());
        
        //select 2 batches to test
        List<Training__c> testTrainings = [SELECT Id FROM Training__c LIMIT 2];

        String[] batchIds = new string[]{};

        for(integer i = 0; i < testTrainings.size(); i++) {
            batchIds.add(testTrainings[i].id);
        }

        //delete 2 batches
        afExternalTrainerBatchesApexController.deleteExtBatchesServer(batchIds);
         
        //confirm that 2 batches were deleted. there were originally 9, so now there should be 7
        system.assertEquals([SELECT Id FROM Training__c].size(), afExternalTrainerBatchesApexController.currentExternalTrainings.size());

        //set a training start date to enter condition loop for null start date
       	//reset property
        afExternalTrainerBatchesApexController.AllExternalTrainings = null;
        List<Training__c> newTrainingsList = [SELECT Id, Name, TrainingTrack__r.ShortName__c, Status__c, TrainingClass__c, StartDate__c, 
                                                     EndDate__c, External_Trainer__r.First_Name__c, External_Trainer__r.Last_Name__c
                                              FROM Training__c
                                              ORDER BY StartDate__c];

        newTrainingsList[0].StartDate__c = null;

        //record EndDate to later assert
        Date nullTest = newTrainingsList[0].EndDate__c;

        system.assertEquals(newTrainingsList.size(), afExternalTrainerBatchesApexController.AllExternalTrainings.size()); 

        afExternalTrainerBatchesApexController.updateExtBatchesServer(newTrainingsList);

        system.assertEquals(newTrainingsList.size(), afExternalTrainerBatchesApexController.AllExternalTrainings.size());

        //negative case, start date = null, assert that the end date is a day before when it began
        system.assertEquals(nullTest.addDays(-1),newTrainingsList[0].EndDate__c);

        //test get trainers by id
        External_Trainer__c testUser = [SELECT id FROM External_Trainer__c LIMIT 1];
        system.assertEquals(afExternalTrainerBatchesApexController.getExtTrainingBatchesById(testUser.Id),
                            [SELECT Id, Name, TrainingTrack__r.ShortName__c, Status__c, TrainingClass__c, StartDate__c, 
                                    EndDate__c, External_Trainer__r.First_Name__c, External_Trainer__r.Last_Name__c
                            FROM Training__c 
                            WHERE Trainer__r.Id = :testUser.id]);

    }
}