force-app/main/default/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Track__c</fullName>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>&quot;Available&quot;</defaultValue>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Skills__c</fullName>
        <description>Contains Training Tracks that the trainer has experience training. When a trainer completes a batch that has a Training Track they had previously not trained, their Training Skills list should be updated to include the new Training Track value.</description>
        <label>Training Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Tracks</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/CurrentLocation__c.field-meta.xml
<CustomField>
    <fullName>CurrentLocation__c</fullName>
    <label>Current Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fairfax</fullName>
            </value>
            <value>
                <fullName>SPS</fullName>
            </value>
            <value>
                <fullName>Reston</fullName>
            </value>
            <value>
                <fullName>UTA-ERB</fullName>
            </value>
            <value>
                <fullName>USF-NEC</fullName>
            </value>
            <value>
                <fullName>ASU</fullName>
            </value>
            <value>
                <fullName>WVU-CBE</fullName>
            </value>
            <value>
                <fullName>Queens</fullName>
            </value>
            <value>
                <fullName>USF-SOC</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>USF-BSN</fullName>
            </value>
            <value>
                <fullName>UTA-PRS</fullName>
            </value>
            <value>
                <fullName>UTA-K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Training_Tracks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Appian BPM</fullName>
    </customValue>
    <customValue>
        <fullName>Big Data/Hadoop</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamics CRM</fullName>
    </customValue>
    <customValue>
        <fullName>ETL/Informatics</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack .NET</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack Java/JEE</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack JTA</fullName>
    </customValue>
    <customValue>
        <fullName>Microservices</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Fusion Middleware</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pega</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>System Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Web Tools</fullName>
    </customValue>
    <description>Batch types available, can be used to keep track of the types of batches that trainers have performed.</description>
    <masterLabel>Training Tracks</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/afTrainersTabListViewApexController.cls
public class afTrainersTabListViewApexController {

   @AuraEnabled
   public static List<User> allTrainers() {
       return [SELECT Id, Name, Available__c, Training_Skills__c, CurrentLocation__c
               FROM User
               WHERE UserRole.Name = 'Trainer' OR UserRole.Name = 'Co-Trainer'];
   }

   @AuraEnabled
   public static String getTrainerSkills(Id trainerId) {
       String returnSkills;

       List<Skill__c> trainerSkills = [SELECT Training_Track__r.ShortName__c
                                       FROM Skill__c
                                       WHERE Trainer__c = :trainerId];

       if(trainerSkills.size() > 0) {
           for(Integer i = 0; i < trainerSkills.size(); i++) {
               if(returnSkills == null) {
                   returnSkills = trainerSkills[i].Training_Track__r.ShortName__c;
               } else {
                   returnSkills += (', ' + trainerSkills[i].Training_Track__r.ShortName__c);
               }
           }
       }
       return returnSkills;
   }
}