force-app/main/default/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Track__c</fullName>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>CoTrainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingClass__c</fullName>
        <formula>RIGHT(TEXT(MONTH(StartDate__c)), 2) + &apos;/&apos; + LPAD(TEXT(DAY(StartDate__c)), 2, &apos;0&apos;) + &apos; - &apos; + TrainingLocation__r.OfficeName__c + &apos; - &apos; + TrainingTrack__r.ShortName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingRoom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Room</label>
        <referenceTo>Training_Room__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingTarget__c</fullName>
        <label>Training Target</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>OfficeName__c</fullName>
        <label>Office Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Training Location</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Training Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Room__c.object
<CustomObject>
    <fields>
        <fullName>AVAvailability__c</fullName>
        <label>A/V Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Upon Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RoomCapacity__c</fullName>
        <label>Room Capacity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingLocationName__c</fullName>
        <formula>TrainingLocation__r.OfficeName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <label>Training Location ID</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Training Rooms</relationshipLabel>
        <relationshipName>Training_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Room</label>
    <nameField>
        <label>Training Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>&quot;Available&quot;</defaultValue>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/afNewBatchAndAvailApexControllerTest.cls
/********************************************************************
* afNewBatchAndAvailApexController Test Class
* Author: Ian Blanchard
*
* Test Class for the Master Apex Controller. This Apex Controller
*   provides the queries for the three components on the Batch tab
*   so that the database can be queried as few times as possible.
*********************************************************************/


@isTest 
public class afNewBatchAndAvailApexControllerTest {
    
    @TestSetup
    public static void doSetup(){

        //Create and Insert 200 Trainers
        List<User> trainers = UtilityMethods.createUserData(200);
        insert trainers;

        //Create and Insert 200 Locations
        List<Training_Location__c> locations = UtilityMethods.createLocationData(200);
        System.runAs(trainers.get(0)) { 
            insert locations;
        }

        //Create and Insert 200 Rooms and Tracks
        List<Training_Room__c> rooms = UtilityMethods.createRoomData(200,locations.get(0));
        List<Training_Track__c> tracks = UtilityMethods.createTrainingTrackData(200);
        System.runAs(trainers.get(0)) {
            insert tracks;
        }

        //Create and Insert 200 Skills and Trainings using the above Trainers, Tracks and Locations
        List<Skill__c> skills = UtilityMethods.createSkillData(200,trainers,tracks);
        List<Training__c> trainings = UtilityMethods.createTrainingsData(200,locations,trainers,new List<Date>{Date.newInstance(2019,3,18)},tracks);
        System.runAs(trainers.get(0)){
            insert rooms;
            insert skills;
            insert trainings;
        }
        
    }

    @isTest
    public static void doTest() {

        test.startTest();

        //Query for the lists inserted in Setup
        List<User> trainers = [SELECT id, Name, Available__c FROM User WHERE UserRole.Name = 'Trainer'];
        List<Training_Location__c> locations = [SELECT id, Name, OfficeName__c FROM Training_Location__c];
        List<Training_Room__c> rooms = [SELECT id, name, TrainingLocation__c, TrainingLocationName__c, AVAvailability__c, RoomCapacity__c FROM Training_Room__c];
        List<Skill__c> skills = [SELECT Training_Track__c, Trainer__c FROM Skill__c];
        List<Training__c> trainings = [SELECT id, Name, CreatedDate, CoTrainer__c, CoTrainer__r.name, 
                                              Trainer__c, Trainer__r.Name, TrainingTarget__c,
                                              TrainingLocation__c, TrainingLocation__r.OfficeName__c, 
                                              TrainingTrack__c, TrainingTrack__r.ShortName__c, TrainingTrack__r.Color__c, 
                                              TrainingClass__c, TrainingRoom__c, StartDate__c, EndDate__c 
                                       FROM Training__c
                                       WHERE Status__c != 'Completed' OR Status__c != 'Cancelled'];

        //Get the results from the Controller methods
        List<User> trainerResults = afNewBatchAndAvailabilityApexController.masterTrainers();
        List<Training_Room__c> roomResults = afNewBatchAndAvailabilityApexController.masterRooms();
        List<Training_Location__c> locationResults = afNewBatchAndAvailabilityApexController.masterLocations();
        List<Skill__c> skillResults = afNewBatchAndAvailabilityApexController.masterSkills();
        List<Training__c> trainingResults = afNewBatchAndAvailabilityApexController.masterOpenTrainings();

        Test.stopTest();

        //Check that the results from the Controller methods match the original lists.
        System.assertEquals(trainers.size(),trainerResults.size());
        System.assertEquals(rooms.size(),roomResults.size());
        System.assertEquals(locations.size(),locationResults.size());
        System.assertEquals(skills.size(),skillResults.size());
        System.assertEquals(trainings.size(),trainingResults.size());
    }

}