force-app/main/default/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>CoTrainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingClass__c</fullName>
        <formula>RIGHT(TEXT(MONTH(StartDate__c)), 2) + &apos;/&apos; + LPAD(TEXT(DAY(StartDate__c)), 2, &apos;0&apos;) + &apos; - &apos; + TrainingLocation__r.OfficeName__c + &apos; - &apos; + TrainingTrack__r.ShortName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>OfficeName__c</fullName>
        <label>Office Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Training Location</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Training Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/afTrainingBatchesApexControllerTest.cls
/*****************************************************
* afTrainingBatchesApexController Test Class
* Author: Sergey Sambros
*
* Tests the Apex Controller for the afTrainingBatches
*   component. 27/27 lines covered
*****************************************************/

@isTest
public class afTrainingBatchesApexControllerTest {
	
    @testSetup 
    public static void testDataSetup() {

        //Setup test data: Locations, Training Tracks, Trainings, User
        //UtilityMethods is last method in this class
        List<Training_Location__c> testL = UtilityMethods.createLocationData(6);
        List<User> testU = UtilityMethods.createUserData(3);       
        List<Training_Track__c> testT = UtilityMethods.createTrainingTrackData(3);
        List<Training__c> testTr = UtilityMethods.createTrainingsData(9, testL, testU,                                          
                                           UtilityMethods.createStartDateData(9), testT);
        //below prevents mixed dml error 
        insert testU;
        System.runAs(testU[0]){
            insert testT;
            insert testL;
            insert testTr;            
        }
    }
       
    @isTest
    public static void doTest() { 

        List <Training__c> AllTrainings = [SELECT Id, Name, TrainingLocation__r.OfficeName__c, 
                                                  TrainingTrack__r.ShortName__c,
                                                  Status__c, TrainingClass__c, StartDate__c, 
                                                  EndDate__c, Trainer__r.Name, CoTrainer__r.Name
                                           FROM Training__c
                                           ORDER BY StartDate__c];

        //test that the soql queries in the controller are as expected
        system.assertEquals(AllTrainings, afTrainingBatchesApexController.AllTrainings);
        system.assertEquals(AllTrainings, afTrainingBatchesApexController.currentTrainings);

        //test getter
        system.assertEquals(AllTrainings, afTrainingBatchesApexController.getTrainingBatches());
        
        //select 2 batches to test
        List<Training__c> testTrainings = [SELECT Id FROM Training__c LIMIT 2];

        String[] batchIds = new string[]{};

        for(integer i = 0; i < testTrainings.size(); i++) {
            batchIds.add(testTrainings[i].id);
        }

        //delete 2 batches
        afTrainingBatchesApexController.deleteBatchesServer(batchIds);
         
        //confirm that 2 batches were deleted 
        system.assertEquals([SELECT Id FROM Training__c].size(), afTrainingBatchesApexController.AllTrainings.size());

        //set a training start date to enter condition loop for null start date
       	//reset property
        afTrainingBatchesApexController.AllTrainings = null;
        List<Training__c> newTrainingsList = [SELECT Id, Name, TrainingLocation__r.OfficeName__c, 
                                                     TrainingTrack__r.ShortName__c,
                                                     Status__c, TrainingClass__c, StartDate__c, 
                                                     EndDate__c, Trainer__r.Name, CoTrainer__r.Name
                                              FROM Training__c];

        newTrainingsList[0].StartDate__c = null;

        //record EndDate to later assert
        Date nullTest = newTrainingsList[0].EndDate__c;

        system.assertEquals(newTrainingsList.size(), afTrainingBatchesApexController.AllTrainings.size()); 

        afTrainingBatchesApexController.updateBatchesServer(newTrainingsList);

        system.assertEquals(newTrainingsList.size(), afTrainingBatchesApexController.AllTrainings.size());

        //negative case, start date = null, assert that the end date is a day before when it began
        system.assertEquals(nullTest.addDays(-1),newTrainingsList[0].EndDate__c);

        //test get trainers by id
        User testUser = [Select id From USER LIMIT 1 OFFSET 2];
        system.assertEquals(afTrainingBatchesApexController.getTrainingBatchesById(testUser.Id),
                            [SELECT Id, Name, TrainingLocation__r.OfficeName__c, TrainingTrack__r.ShortName__c,
                                    Status__c, TrainingClass__c, StartDate__c, EndDate__c, 
                                    Trainer__r.Name, CoTrainer__r.Name
                            FROM Training__c 
                            WHERE Trainer__r.Id = :testUser.id]);
                            
    }   

}