force-app/main/default/objects/Training_Room__c.object
<CustomObject>
    <fields>
        <fullName>RoomCapacity__c</fullName>
        <label>Room Capacity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingLocationName__c</fullName>
        <formula>TrainingLocation__r.OfficeName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Location</label>
        <type>Text</type>
    </fields>
    <label>Training Room</label>
    <nameField>
        <label>Training Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/afNewBatchFormApexController.cls
public class afNewBatchFormApexController {
    
    @AuraEnabled 
    public static User getExternalTrainerUser(){
        return [SELECT Id FROM User WHERE Name='External Trainer' LIMIT 1];
    }
    
    @AuraEnabled
	public static List<Training_Room__c> filterRoomByLocation(String location, Double capacity, List<Training_Room__c> allRooms ){
		// New list that will store filtered rooms 
        List<Training_Room__c> filteredRooms = new List<Training_Room__c>();

        if(location != '' || location != null){
            for(Training_Room__c room : allRooms){
                // If the location are in the input add to list  
                if(location == room.TrainingLocationName__c && capacity <= room.RoomCapacity__c)
                    filteredRooms.add(room);
            }
            return filteredRooms;
        }
        
        
        return allRooms;
    }
}