src/objects/PTO__c.object
<CustomObject>
    <description>Paid Time Off</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Needs to be Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PTO</label>
    <nameField>
        <displayFormat>PTO-{00000}</displayFormat>
        <label>PTO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/afProfileInfoController.cls
public class afProfileInfoController {
    
    @AuraEnabled
    public static ContentDocument getFile(Id userId){
        return [SELECT Id, Title FROM ContentDocument WHERE CreatedbyId = :userId ORDER BY CreatedDate DESC LIMIT 1];
    }
    
    @AuraEnabled
    public static List<PTO__c> getPTO(Id userId){
        return [SELECT StartDate__c, EndDate__c, Status__c, Trainer__c FROM PTO__c WHERE Trainer__c = :userId];
    }
}