src/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Track__c</fullName>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>CoTrainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Track__c.object
<CustomObject>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/afTrainingTriggerHelper.cls
public class afTrainingTriggerHelper {
    
    public static void createSkills(List<Training__c> trainings){
        Boolean trainerHasSkill = false;
        Boolean cotrainerHasSkill = false; 
        List<Skill__c> skillsToCreate = new List<Skill__c>();
        List<Skill__c> allSkills = [SELECT Trainer__c, Training_Track__c FROM Skill__c];
        for(Training__c training: trainings){
            for(Skill__c skill: allSkills){
                if(training.Trainer__c==skill.Trainer__c && training.TrainingTrack__c==skill.Training_Track__c){
                    trainerHasSkill = true;
                } 
                if(training.CoTrainer__c!=null &&training.CoTrainer__c==skill.Trainer__c && training.TrainingTrack__c==skill.Training_Track__c){
                    cotrainerHasSkill = true;
                }
            }
            if(trainerHasSkill!=true){
                Skill__c newSkill = new Skill__c();
                newSkill.Trainer__c = training.Trainer__c;
                newSkill.Training_Track__c = training.TrainingTrack__c;
                skillsToCreate.add(newSkill);
            }
            if(training.CoTrainer__c!=null && cotrainerHasSkill!=true){
                Skill__c newSkill = new Skill__c();
                newSkill.Trainer__c = training.Trainer__c;
                newSkill.Training_Track__c = training.TrainingTrack__c;
                skillsToCreate.add(newSkill);
            }
            trainerHasSkill = false;
            cotrainerHasSkill = false; 
        }
        insert skillsToCreate;
    }
    
}