src/objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>OfficeName__c</fullName>
        <label>Office Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Training Location</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Training Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Room__c.object
<CustomObject>
    <fields>
        <fullName>AVAvailability__c</fullName>
        <label>A/V Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Upon Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <label>Training Location ID</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Training Rooms</relationshipLabel>
        <relationshipName>Training_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Room</label>
    <nameField>
        <label>Training Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>&quot;Available&quot;</defaultValue>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/afAvailListContainerApexControllerTest.cls
@isTest
public class afAvailListContainerApexControllerTest {

    @testSetup
    public static void insertTestData(){
        Training_Location__c loc = new Training_Location__c();
        loc.OfficeName__c = 'testPlace';
        insert loc;
        List<Training_Room__c> testRooms = new List<Training_Room__c>();
        for(Integer i=0; i<60; i++){
            Training_Room__c tr = new Training_Room__c();
            if(math.mod(i, 3)==0){
                tr.AVAvailability__c='Yes';
            } else if(math.mod(i,3)==1){
                tr.AVAvailability__c='No';
            } else{
                tr.AVAvailability__c='Upon Request';
            }
            tr.TrainingLocation__c = [Select Id FROM Training_Location__c LIMIT 1].Id;
            testRooms.add(tr);
        }
        insert testRooms;
    }
    @isTest
    public static void testGetRooms(){
        System.assertEquals(60, afAvailListContainerApexController.getRooms().size());
        System.assertEquals('Yes', afAvailListContainerApexController.getRooms()[10].AVAvailability__c);
        System.assertEquals('No', afAvailListContainerApexController.getRooms()[21].AVAvailability__c);
        System.assertEquals('Upon Request', afAvailListContainerApexController.getRooms()[50].AVAvailability__c);
    }
    @isTest
    public static void testGetTrainers(){
        List<User> availableUsers = [SELECT Id, Name, Available__c
                                         FROM User 
                                         WHERE UserRole.Name = 'Trainer' OR UserRole.Name = 'CoTrainer' Order By Available__c];
        System.assertEquals(availableUsers, afAvailListContainerApexController.getAllTrainers());
        
    }
}