src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>CoTrainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingClass__c</fullName>
        <formula>RIGHT(TEXT(MONTH(StartDate__c)), 2) + &apos;/&apos; + LPAD(TEXT(DAY(StartDate__c)), 2, &apos;0&apos;) + &apos; - &apos; + TrainingLocation__r.OfficeName__c + &apos; - &apos; + TrainingTrack__r.ShortName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainingLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>OfficeName__c</fullName>
        <label>Office Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Training Location</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Training Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <label>Short Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/afTrainingBatchesApexController.cls
public class afTrainingBatchesApexController{

   public static List<Training__c> AllTrainings
   {
       get{
           if(AllTrainings == null)
           {
               AllTrainings = [SELECT Id, Name, TrainingLocation__r.OfficeName__c, TrainingTrack__r.ShortName__c,
                               Status__c, TrainingClass__c, StartDate__c, EndDate__c, Trainer__r.Name, CoTrainer__r.Name
                               FROM Training__c
                               ORDER BY StartDate__c];
           }

           return AllTrainings;
       }
       set;
   }

   @AuraEnabled
   public static List<Training__c> currentTrainings
   {
       get{
           if(currentTrainings == null)
           {
               currentTrainings = AllTrainings;
           }
           return currentTrainings;
       }
       set;
   }

   @AuraEnabled
   public static List<Training__c> getTrainingBatches() {
       return AllTrainings;
   }
    
    @AuraEnabled
    public static void deleteBatchesServer(String[] batchIds)
    {
       // Map<String, String> Objects = new Map<String, String>();
      
        List<Training__c> batchesToDelete = new List<Training__c>();
        
        for(integer s = 0; s < batchIds.size(); s++){
                batchesToDelete.add(new Training__c(Id = batchIds[s]));
            }
        
        /*
        List<SObject> batches = new List<SObject>();
        for(integer i = 0; i < AllTrainings.size(); i++){
            for(integer j = 0; j < batchIds.size()-1; j++){
                if(AllTrainings[i].id == batchIds[j] )
                {
                    batches.add(AllTrainings[i]);
                }
            }
        }*/
        delete batchesToDelete; 
    }
    
    @AuraEnabled
    public static void updateBatchesServer(List<Training__c> updatedBatches){
		System.debug('Batches to Update: ' + updatedBatches);
        /*
        List<Training__c> batchesToUpdate = new List<Training__c>();
        
        for(integer s = 0; s < updatedBatches.size(); s++){
                batchesToUpdate.add(new Training__c(updatedBatches[s]));
        }*/
        update updatedBatches;
        System.debug('Update ran on batches');
    }

}