src/objects/Training_Room__c.object
<CustomObject>
    <fields>
        <fullName>AVAvailability__c</fullName>
        <label>A/V Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Upon Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RoomCapacity__c</fullName>
        <label>Room Capacity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainingLocationName__c</fullName>
        <formula>TrainingLocation__r.OfficeName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Location</label>
        <type>Text</type>
    </fields>
    <label>Training Room</label>
    <nameField>
        <label>Training Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/afAvailbilityListContainerController.cls
public class afAvailbilityListContainerController {
        
    public static List<Training_Room__c> allRooms = [SELECT Id, name, TrainingLocationName__c, AVAvailability__c, RoomCapacity__c
                                              FROM Training_Room__c
                                              ORDER BY name];
    
    @AuraEnabled
    public static List<Training_Room__c> getRooms(){
        List<Training_Room__c> sorted = new List<Training_Room__c>();
        
        for(Training_Room__c room : allRooms){
            if(room.AVAvailability__c == 'Yes'){
                sorted.add(room);
            }
        }
        for(Training_Room__c room : allRooms){
            if(room.AVAvailability__c == 'Upon Request'){
                sorted.add(room);
            }
        }
        for(Training_Room__c room : allRooms){
            if(room.AVAvailability__c == 'No'){
                sorted.add(room);
            }
        }
        return sorted;
    }
}