src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>&quot;Available&quot;</defaultValue>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Skills__c</fullName>
        <description>Contains Training Tracks that the trainer has experience training. When a trainer completes a batch that has a Training Track they had previously not trained, their Training Skills list should be updated to include the new Training Track value.</description>
        <label>Training Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Tracks</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Training_Tracks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Appian BPM</fullName>
    </customValue>
    <customValue>
        <fullName>Big Data/Hadoop</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamics CRM</fullName>
    </customValue>
    <customValue>
        <fullName>ETL/Informatics</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack .NET</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack Java/JEE</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack JTA</fullName>
    </customValue>
    <customValue>
        <fullName>Microservices</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Fusion Middleware</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pega</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>System Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Web Tools</fullName>
    </customValue>
    <description>Batch types available, can be used to keep track of the types of batches that trainers have performed.</description>
    <masterLabel>Training Tracks</masterLabel>
</GlobalValueSet>

src/classes/afAvailabilityListContainerController.cls
public class afAvailabilityListContainerController {
    public static List<User> Trainers = [SELECT Id, Name, Available__c, Training_Skills__c From User OrderByName /*WHERE Available__c!=null*/ /*UserRoleId=trainer role Id*/];
    @AuraEnabled
    public static List<User> getAllTrainers(){
        //Must add a WHERE clause UserRoleId=Trainer Role Id
        List<User> availableList = new List<User>();
        List<User> unavailableList = new List<User>();
        for(User t: Trainers){
            if(t.Available__c=='Available'){
                availableList.add(t);
            }else{
                unavailableList.add(t);
            }
        }
        availableList.addAll(unavailableList);
        system.debug(availableList);
        return availableList;
    }

}