src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>&quot;Available&quot;</defaultValue>
        <label>Available</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OOO</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Skills__c</fullName>
        <description>Contains Training Tracks that the trainer has experience training. When a trainer completes a batch that has a Training Track they had previously not trained, their Training Skills list should be updated to include the new Training Track value.</description>
        <label>Training Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Tracks</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/CurrentLocation__c.field-meta.xml
<CustomField>
    <fullName>CurrentLocation__c</fullName>
    <label>Current Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fairfax</fullName>
            </value>
            <value>
                <fullName>SPS</fullName>
            </value>
            <value>
                <fullName>Reston</fullName>
            </value>
            <value>
                <fullName>UTA-ERB</fullName>
            </value>
            <value>
                <fullName>USF-NEC</fullName>
            </value>
            <value>
                <fullName>ASU</fullName>
            </value>
            <value>
                <fullName>WVU-CBE</fullName>
            </value>
            <value>
                <fullName>Queens</fullName>
            </value>
            <value>
                <fullName>USF-SOC</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>USF-BSN</fullName>
            </value>
            <value>
                <fullName>UTA-PRS</fullName>
            </value>
            <value>
                <fullName>UTA-K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Training_Tracks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Appian BPM</fullName>
    </customValue>
    <customValue>
        <fullName>Big Data/Hadoop</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamics CRM</fullName>
    </customValue>
    <customValue>
        <fullName>ETL/Informatics</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack .NET</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack Java/JEE</fullName>
    </customValue>
    <customValue>
        <fullName>Full Stack JTA</fullName>
    </customValue>
    <customValue>
        <fullName>Microservices</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Fusion Middleware</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pega</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>System Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Web Tools</fullName>
    </customValue>
    <description>Batch types available, can be used to keep track of the types of batches that trainers have performed.</description>
    <masterLabel>Training Tracks</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/createTrainers.cls
public class createTrainers {

    public static void createTrainers() {
        List<String> lastNames = new List<String> {'Alagna', 'Bonds', 'Colson', 'Donnelly', 'Goshorn', 'Greer', 'Higgens', 'Hill', 'Jurczak',
            'Knighten', 'Kumar', 'Lessley', 'Orr', 'Rehm', 'Trainer'};
        List<String> firstNames = new List<String> {'Peter', 'Genesis', 'Jessica', 'Quintin', 'Mitchell', 'Damon', 'Emily', 'Harvey', 'Nickolas',
            'Jason', 'Arun', 'Ryan', 'Richard', 'Carolyn', 'External'};
                        
        ID profID = [SELECT Id FROM Profile WHERE Name = 'Trainer' LIMIT 1].id;
        ID roleID = [SELECT id,name FROM UserRole WHERE name = 'Trainer' LIMIT 1].id;
        
        List<User> trainers = new List<User>();
        
        for (Integer i = 0; i < lastNames.size(); i++) {
            User u1 = new User(ProfileId=profID, LastName=lastNames[i], FirstName=firstNames[i], Email='assignforcerevature@gmail.com', username=lastNames[i] + '@HarryMitchellaf3.com', 
                               CompanyName='Revature', Title='Trainer', Alias=firstNames[i], TimeZoneSidKey='America/New_York', EmailEncodingKey='UTF-8',
                               LanguageLocaleKey='en_US',LocaleSidKey='en_US', Available__c='Available',UserRoleId=roleID, isActive=false);
            trainers.add(u1);
        }
        
        insert trainers;
    }
    
    public static void AssignLocations(){
        Schema.DescribeFieldResult locFr = User.CurrentLocation__c.getDescribe();
        Schema.DescribeFieldResult skillFr = User.Training_Skills__c.getDescribe();
        List<Schema.PicklistEntry> locPlEntries = locFr.getPicklistValues();
        List<Schema.PicklistEntry> skillPlEntries = skillFr.getPicklistValues();
        List<String> locNames = new List<String>();
        List<String> skillNames = new List<String>();

        for (Schema.PicklistEntry entry : locPlEntries){
            locNames.add(entry.getLabel());
        }
        for (Schema.PicklistEntry entry : skillPlEntries){
            skillNames.add(entry.getLabel());
        }
        Integer numLocs = locNames.Size();
        Integer numSkills = skillNames.Size();
        UserRole trainerRole = [select id, name from UserRole where name='Trainer'];
        
        List<User> usrs = [select id from User where UserRoleId=:trainerRole.Id];
        for (User usr : usrs){
            usr.CurrentLocation__c = locNames[Integer.valueof((Math.random() * numLocs))];
            usr.Training_Skills__c = skillNames[Integer.valueof((Math.random() * numSkills))];
        }
        
        update usrs;
    }
}